Feature/217
JNU-Parking-Ticket-Project/Parking-Ticket-FE pull request #218
Opened 2024-08-06 13:21 UTC by loopy-lim

## 주요 변경사항

- 여러 사람이 신청 버튼을 여러개 눌렀을 때 메모리 초과 오류가 나는 것을 발견.
- 이를 해결하기 위해 Apply의 마지막 신호만 가게 만듦.
- Captcha를 불러오는 중에 button을 못 누르게 만들기
- Apply시에 debounce 적용하기

## 리뷰어에게...

- 검증되지 않았습니다.
- 현재 Test BE서버가 활성화 되고, 한번 테스트 해주시기 바랍니다.(특히 debounce 관련해서... 😢 )

## 관련 이슈

- closes #217

2024-08-06 13:48 UTC, j8won reviewed
수고하셨습니다~!

`ApplyForm`에서 추가된 기능이 결과적으로는 사용자에게 친절하게 UI로 api 통신이 늦어지고 있음을 보여주는 역할이라고 생각하는데, 이 기능이 `ApplyForm` 뿐만 아니라 `CaptchaForm`의 제출 버튼에도 있으면 좋을 것 같아요. 결과적으로 최종신청은 `CaptchaForm`의 버튼의 역할이라서요.

만약 `CaptchaForm`의 버튼에도 로딩 스피너가 추가된다면 `useApply`의 디바운싱은 굳이 추가하지 않아도 된다고 생각합니다.

2024-08-06 13:48 UTC, j8won commented on service-apply/src/components/apply/ApplyForm.tsx
> +          <Suspense fallback={<Spinner></Spinner>}>
```suggestion
          <Suspense fallback={<Spinner />}>
```
이렇게 수정하는 건 어떨까요

2024-08-06 14:08 UTC, loopy-lim commented on service-apply/src/components/apply/ApplyForm.tsx
> +          <Suspense fallback={<Spinner></Spinner>}>
저도 동의합니다. 감사합니다 ㅠㅠㅠㅠㅠ [8e0e7d1](https://github.com/JNU-Parking-Ticket-Project/Parking-Ticket-FE/pull/218/commits/8e0e7d132d041a1827b06abcba98ee0866e64e0a)

2024-08-06 14:24 UTC, j8won commented on service-apply/src/components/apply/ApplyForm.tsx
> +          <Suspense fallback={<Spinner></Spinner>}>
화이팅!!!!

2024-08-07 07:47 UTC, 2yunseong requested changes
https://w1693204506-pd7529286.slack.com/archives/C05RZK7AB08/p1723016753822549?thread_ts=1722950013.784109&cid=C05RZK7AB08

2024-08-08 01:38 UTC, loopy-lim commented
debounce보다, disabled와 useMutation의 status옵션을 사용하여 구현을 하는 것이 더 좋다고 생각하여 구현의 방식을 변경하였습니다.

2024-08-09 10:48 UTC, 2yunseong approved these changes
LGTM~~

2024-08-09 11:46 UTC, j8won approved these changes
👍 👍 👍

2024-08-11 13:34 UTC, merged