fix: response가 ok가 아닌 경우 error response를 반환한다.
JNU-Parking-Ticket-Project/Parking-Ticket-FE pull request #243
Opened 2024-10-17 14:42 UTC by loopy-lim

## 주요 변경사항

ok가 아닌 경우 error response를 반환하게 하였습니다.
ok인 경우에는 200~299의 http가 올 때입니다.
- https://developer.mozilla.org/en-US/docs/Web/API/Response/ok

추가적으로 editor에 어떠한 방법이든 이미지를 넣을려고 할 때 alert로  넣을 수 없다고 알려주고 업로드를 방지하였습니다.

<img width="1407" alt="스크린샷 2024-10-17 오후 11 38 16" src="https://github.com/user-attachments/assets/2cbff72b-ab7c-411a-935d-5da91d90978c">

## 리뷰어에게...

- 근본적인 사용자 방지도 추가하였습니다.

## 관련 이슈

- closes #240

2024-10-18 02:45 UTC, smb0123 approved these changes
고생하셨습니다 ~

2024-10-18 06:00 UTC, 2yunseong requested changes

2024-10-18 06:56 UTC, loopy-lim commented on service-apply/src/functions/https.ts
> +    return response;
[fcca9f9](https://github.com/JNU-Parking-Ticket-Project/Parking-Ticket-FE/pull/243/commits/fcca9f90082d5ab9a507b850ab1a855f1c75dd42)

오... 맞아요... 어제 머가 씌웠나바요
좀 더 생각했을 때, 저희 문서화 할 때 403, 401같은 에러들을 처리해야할지, 아니면 error status를 따로 해야할지 고민해봐야할지도 고민해야겠네요...

2024-10-19 01:41 UTC, 2yunseong approved these changes
👍  차차 고민해봅시다

2024-10-19 01:42 UTC, merged