feat: 공지사항 이미지 기능 추가
JNU-Parking-Ticket-Project/Parking-Ticket-FE pull request #251
Opened 2024-11-29 12:34 UTC by smb0123

## 주요 변경사항
- 공지사항 생성 페이지에서 이미지 등록, 삭제 기능 추가, 
- 공지사항 상세 페이지에서 등록한 이미지 확인 기능 추가
- 공지사항 수정 페이지에서 등록한 이미지 수정 기능 추가
- 공지사항 이미지 클릭 시 모달 렌더링

## 리뷰어에게...
- 아직 백엔드 서버에 이미지 관련한 수정 사항이 아직 반영되지 않아서 테스트 후에 PR을 올릴려고 했으나 다음 주차권 시행일이 얼마 남지 않아서 PR을 먼저 올렸습니다. 추후에 백엔드 서버에 이미지 관련 내용이 추가된 후 테스트까지 완료하면 merge 하겠습니다. 
- 궁금한 사항이 있는데 한 파일에는 하나의 컴포넌트만 작성해야 하는지 궁금합니다 !

## 관련 이슈

- closes #250 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정

2024-11-29 16:30 UTC, 2yunseong commented
내일 리뷰 남겨둘께요~ 고생하셨어요

2024-11-30 02:19 UTC, 2yunseong requested changes
고생하셨어요~ 일단 한가지만 확인 부탁드립니다.

> 궁금한 사항이 있는데 한 파일에는 하나의 컴포넌트만 작성해야 하는지 궁금합니다 !

꼭 그런건 아니라고 생각해요. 얼만큼의 책임을 가질지 설계 하냐에 따라 달라지지 않을까요??
어떤 상황에서 그런 고민이 나왔는지 자세하게 설명을 듣고 싶네요~!

2024-11-30 02:19 UTC, 2yunseong commented on service-manager/src/components/announcement/AnnouncementAddImg.tsx
> +      />
파일의 확장자를 제한해주면 좋을 거 같습니다 :)

2024-11-30 05:37 UTC, loopy-lim requested changes
몇가지만 준수해서 봐주시면 감사할 것 같아요

2024-11-30 05:37 UTC, loopy-lim commented on service-manager/src/apis/dtos/announce.dtos.ts
> +  imageUrl: string[];
apis에서는 `imageUrls`로 적으셨는데 여기서는 `imageUrl`이라서 통일이 있으면 좋을 것 같아요.

2024-11-30 05:37 UTC, loopy-lim commented on service-manager/src/assets/close.png
png도 좋고 svg도 좋긴 한데, 아이콘 계열들은 거의 svg계열이면 좋을 것 같아요

2024-12-01 09:31 UTC, smb0123 commented
> 꼭 그런건 아니라고 생각해요. 얼만큼의 책임을 가질지 설계 하냐에 따라 달라지지 않을까요?? 어떤 상황에서 그런 고민이 나왔는지 자세하게 설명을 듣고 싶네요~!
1. 프로젝트에서 컨벤션으로 한 파일에 하나의 컴포넌트만 작성해야 한다라는 컨벤션이 있는지 궁금했어요.
2. 그리고 그런 컨벤션이 없다면 AnnouncementImgList 컴포넌트와 AnnouncementImg 컴포넌트를 봤을 때 제 생각에는 현재도 AnnouncementImg는 AnnouncementImgList에서만 사용하고 있고 앞으로도 다른 곳에서 사용하지 않을 것 같아서 같은 파일에 작성하였습니다. 두 컴포넌트를 같이 작성하는 것에 대해 어떻게 생각하시는지 궁금합니다.

2024-12-01 10:18 UTC, smb0123 commented on service-manager/src/components/announcement/AnnouncementAddImg.tsx
> +      const extension = files[0].name.split('.')[1];
오 감사합니다 ! 그런 예외 상황에 대해 생각을 못하고 있었어요. 아래 코드와 같이 변경하겠습니다.
```
const fileName = files[0].name;
const extension = fileName.split('.')[fileName.split('.').length - 1];
```

2024-12-01 11:00 UTC, smb0123 commented on service-manager/src/components/announcement/AnnouncementAddImg.tsx
> +              }
멋있네요 ! 👍

2024-12-01 11:18 UTC, smb0123 commented on service-manager/src/components/announcement/AnnouncementAddImg.tsx
> +export function AnnouncementAddImg({ setImages }: AnnouncementAddImgProps) {
알겠습니다 !

2024-12-01 11:26 UTC, smb0123 commented on service-manager/src/components/announcement/AnnouncementAddImg.tsx
> +        });
async await를 사용하면 될 것 같습니다 !

2024-12-01 12:09 UTC, loopy-lim commented on service-manager/src/components/announcement/AnnouncementAddImg.tsx
> +      const extension = files[0].name.split('.')[1];
좀 더 맛있게 하고 싶으시다면 다음과 같은 형식도 좋아요.
const extension = files[0].name.split('.').at(-1);

2024-12-01 12:09 UTC, loopy-lim commented on service-manager/src/components/announcement/AnnouncementAddImg.tsx
> +        });
try catch도 혼용해서 함수로 빼낸다면 더 이쁜 코드가 될지 않을까 라는 생각이 듭니다.

2024-12-01 12:11 UTC, smb0123 commented on service-manager/src/components/announcement/AnnouncementAddImg.tsx
> +      const extension = files[0].name.split('.')[1];
오 at이 더 좋겠네요. 감사합니다 !

2024-12-01 12:20 UTC, smb0123 commented on service-manager/src/components/announcement/AnnouncementAddImg.tsx
> +        });
어떤 방식인지 이해가 가지 않아서 자세하게 설명해주실 수 있을까용 ??

2024-12-01 12:32 UTC, loopy-lim commented on service-manager/src/components/announcement/AnnouncementAddImg.tsx
> +        });
이렇게 함수로 빼서 줄이거나,
```tsx
  const setNewImage = () => {
    const url = new URL(res.presignedUrl);
    const fileName = url.pathname.slice(1);

    if (setImages) {
      setImages((prev) => [
        ...prev,
        new URL(
          fileName,
          import.meta.env.VITE_IMAGE_BASE_URL,
        ).toString(),
      ]);
    }
  }
  putImageToS3(
    res.presignedUrl,
    new File([files[0]], files[0].name),
    extension,
  )
    .then(setNewImage)
    .catch(() => {
      alert('이미지 업로드에 실패했습니다.');
    });
```
이렇게 해도 되고, 
```tsx
  const setNewImage = () => {
    const url = new URL(res.presignedUrl);
    const fileName = url.pathname.slice(1);

    if (setImages) {
      setImages((prev) => [
        ...prev,
        new URL(
          fileName,
          import.meta.env.VITE_IMAGE_BASE_URL,
        ).toString(),
      ]);
    }
  }
try {
  await putImageToS3(
    res.presignedUrl,
    new File([files[0]], files[0].name),
    extension,
  ) 
}catch () {
   alert('이미지 업로드에 실패했습니다.');
};
setNewImage();
```
이렇게 해도 되고,
```tsx
  const setNewImage = () => {
    const url = new URL(res.presignedUrl);
    const fileName = url.pathname.slice(1);

    if (setImages) {
      setImages((prev) => [
        ...prev,
        new URL(
          fileName,
          import.meta.env.VITE_IMAGE_BASE_URL,
        ).toString(),
      ]);
    }
  }

await putImageToS3(
  res.presignedUrl,
  new File([files[0]], files[0].name),
  extension,
) .catch(() => {
 alert('이미지 업로드에 실패했습니다.');
});
setNewImage();
```

여러가지 방법이 있지 않을까요? 가장 좋은 방법을 선택해보세요

2024-12-02 02:25 UTC, loopy-lim reviewed
몇가지 더 확인해주세용

2024-12-02 02:25 UTC, loopy-lim commented on service-manager/src/components/announcement/AnnouncementAddImg.tsx
> +        if (error instanceof Error) {
필요없는 가드가 아닌가요?

2024-12-02 02:25 UTC, loopy-lim commented on service-manager/src/functions/announcement.ts
> +};
여기서 `setImageUrls`는 react에서 사용하는 친구라서 여기에서 사용하는 것이 과연 좋을지 잘 모르겠습니다.

2024-12-02 05:04 UTC, smb0123 commented on service-manager/src/components/announcement/AnnouncementAddImg.tsx
> +        if (error instanceof Error) {
![image](https://github.com/user-attachments/assets/fdd98fef-dc99-440c-bb6c-e92982498072)
Error 타입을 지정해주지 않으면 타입스크립트 에러가 발생해서 가드를 넣었습니다.

2024-12-02 07:07 UTC, loopy-lim commented on service-manager/src/functions/announcement.ts
> +};
네네 쓴다면 훅이 더 좋을 수도 있을 것 같네요(imageUrls, setImageUrls) 둘다요

2024-12-02 07:07 UTC, 2yunseong commented on service-manager/src/components/announcement/AnnouncementAddImg.tsx
> +              }
옵셔널 체이닝 좋네요

2024-12-02 07:10 UTC, 2yunseong approved these changes
> 그리고 그런 컨벤션이 없다면 AnnouncementImgList 컴포넌트와 AnnouncementImg 컴포넌트를 봤을 때 제 생각에는 현재도 AnnouncementImg는 AnnouncementImgList에서만 사용하고 있고 앞으로도 다른 곳에서 사용하지 않을 것 같아서 같은 파일에 작성하였습니다. 두 컴포넌트를 같은 파일에 작성하는 것에 대해 어떻게 생각하시는지 궁금합니다

괜찮은거 같은데 분리하고 싶게 생기긴 했네요 ㅋㅋ

고생하셨습니다 저는 이만 Approve 할게요!
채승 리뷰 끝나면 merge해주세요~

2024-12-02 14:08 UTC, smb0123 commented on service-manager/src/functions/announcement.ts
> +};
> 네네 쓴다면 훅이 더 좋을 수도 있을 것 같네요(imageUrls, setImageUrls) 둘다요

훅으로 변경완료 했습니다 !

2024-12-02 14:19 UTC, loopy-lim approved these changes
좋습니다!!

2024-12-02 14:24 UTC, merged